import localFont from "next/font/local";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Footer, Navbar } from "@/components";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: 'Home - Chennai Trail Club',
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const router = useRouter();
  // const [pageTitle, setPageTitle] = useState('My Next.js App');
  
  // useEffect(() => {
  //   const handleRouteChange = (url) => {
  //     const newTitle = getPageTitle(url);
  //     setPageTitle(newTitle);
  //   };
  //   setPageTitle(getPageTitle(router.pathname));
  //   router.events.on('routeChangeComplete', handleRouteChange);
  //   return () => {
  //     router.events.off('routeChangeComplete', handleRouteChange);
  //   };
  // }, [router]);
  // const getPageTitle = (path) => {
  //   switch(path){
  //     case '/':
  //       return 'Home - Chennai Trail Club';
  //     case '/aboutus':
  //       return 'About Us - Chennai Trail Club';
  //     case '/pastevents':
  //       return 'Past Events - Chennai Trail Club';
  //     case '/jhu':
  //       return 'Jawadhu Hills Ultra(JHU 2024) - Chennai Trail Club';
  //     case '/upcomingevents':
  //       return 'Upcoming Events - Chennai Trail Club';
  //     case '/privacypolicy':
  //       return 'Privacy Policy - Chennai Trail Club';
  //     case '/register':
  //       return 'Register - Chennai Trail Club';
  //     case '/termsofservice':
  //       return 'Terms of Service - Chennai Trail Club';
  //     case '/refundandcancellation':
  //       return 'Refund and Cancellation - Chennai Trail Club'
  //   }
  // }
  return (
    <html lang="en">
      {/* <Head>
        <title>{pageTitle}</title>
      </Head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-serif`}
      >
        <Navbar/>
        {children}
       <Footer/>
      </body>
    </html>
  );
}
