export const registerContent = [
  {
    key: "1",
    title: "Personal Details",
    fields: [
      {
        name: "runningCategory",
        label: "Select your Running Category",
        type: "select",
        options: ["30KM (INR 1800)", "60KM (INR 2200)"],
        id: "runningCategory",
      },
      { name: "firstName", label: "First Name", type: "text" },
      { name: "lastName", label: "Last Name", type: "text" },
      { name: "mobile", label: "Mobile", type: "tel" },
      { name: "email", label: "Email", type: "email" },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        options: ["Male", "Female", "Prefer Not To Say"],
      },
      {
        name: "dateOfBirth",
        label: "Date of Birth",
        type: "date",
        min: "1960-01-01",
        max: "2006-12-31",
      },
      {
        name: "tShirtSize",
        label: "Select Your T-shirt Size",
        type: "select",
        options: [
          "XS (33)",
          "S (35)",
          "M (38)",
          "L (41)",
          "XL (44)",
          "2XL(47)",
          "3XL(51)",
          "4XL(54)",
        ],
      },
      { name: "address", text: "Address", type: "address" },
      { name: "city", label: "City", type: "text" },
      {
        name: "state",
        label: "State/Province/Region",
        type: "select",
        options: [
          "Andaman and Nicobar Islands",
          "Andhra Pradesh",
          "Arunachal Pradesh",
          "Assam",
          "Bihar",
          "Chandigarh",
          "Chhattisgarh",
          "Dadra and Nagar Haveli",
          "Daman and Diu",
          "Delhi",
          "Goa",
          "Gujarat",
          "Haryana",
          "Himachal Pradesh",
          "Jammu and Kashmir",
          "Jharkhand",
          "Karnataka",
          "Kerala",
          "Ladakh",
          "Lakshadweep",
          "Madhya Pradesh",
          "Maharashtra",
          "Manipur",
          "Meghalaya",
          "Mizoram",
          "Nagaland",
          "Odisha",
          "Puducherry",
          "Punjab",
          "Rajasthan",
          "Sikkim",
          "Tamil Nadu",
          "Telangana",
          "Tripura",
          "Uttar Pradesh",
          "Uttarakhand",
          "West Bengal",
        ],
      },
    ],
  },
  {
    key: "2",
    title: "Other Details",
    fields: [
      {
        name: "bloodGroup",
        label: "Blood Group",
        type: "select",
        options: ["B-", "B+", "O-", "O+", "A-", "A+", "AB-", "AB+"],
      },
      { name: "bibName", label: "Name on BIB", type: "text" },
      {
        name: "runningClub",
        label: "Running Club you are part of",
        type: "select",
        options: [
          "CTC",
          "20Cube Sprinters",
          "Addida Runners - Bengaluru",
          "AFMC Marathan Club",
          "Ajeya Runners",
          "Amdavad Distance Runners",
          "Anagai Running Group",
          "Anakaputhur Running Group",
          "Aristo Runners",
          "ASICS Running Club - Chennai",
          "Badaga Runners",
          "Bandit Runners",
          "Baroda Runners",
          "BCT Runners",
          "Bollineni Runners",
          "BU Runners",
          "Burners",
          "Chetpet Ecopark Fadafat",
          "CISCO Runners",
          "CMC",
          "Coimbatore Runners",
          "Cool Runners",
          "CR - Ambattur Arimas",
          "CR - Bessie Flyers",
          "CR - Chrompet Cheetahs",
          "CR - Coastal Runners",
          "CR - Forest Gumps",
          "CR - Kilpauk Striders",
          "CR - Marina Minnals",
          "CR - Mogappair Fitness Circle",
          "CR - Nungambakkam Nitros",
          "CR - OMR Trailblazers",
          "CR - Pettai Rappers",
          "CR - Pillar Pacers",
          "CR - Porur Racers",
          "CR - T-Nagar Trendsetters",
          "CR - Tambaram Thunderbolts",
          "CR - Tower Twisters",
          "CR - Vibrant Velachery",
          "CT Scullers",
          "CTC - ARB Runners",
          "Decathlon Running Club",
          "DR - Airport Dreamers",
          "DR - Anna Nagar Dreamers (AND)",
          "DR - Avadi Dreamers",
          "DR - Bessie Dreamers",
          "DR - Boat Club Dreamers",
          "DR - Marina Dreamers",
          "DR - Medavakkam Dreamers",
          "DR - MRC Dreamers",
          "DR - OMR Dreamers",
          "DR - RUN T-Nagar RUN",
          "DR - Velachery Dreamers",
          "DR - VMR Dreamers",
          "EC Runners",
          "Erode Runners",
          "F.A.R",
          "F3 Fitness Group",
          "FantasticFour",
          "Fasttrack GYM",
          "Fasttrack GYM",
          "FBTR",
          "Fit Ka-ching",
          "Fitizen",
          "FitMonks",
          "FLS Joggers",
          "Flying Feet",
          "Fort Runners - Palakkad",
          "Friends Fun Fitness - F3",
          "Get-In Get-Fit",
          "Hubbali Fitness Club",
          "Hyderabad Runners",
          "Ideal Runners Club",
          "INCG",
          "ITEN Runners Club",
          "ITPCL Runners",
          "Jayanagar Jaguars",
          "JGA Jaguars",
          "Jolly Runners",
          "Kakching Runners",
          "Kamakoti Gallopers",
          "Kavach Runners",
          "KaysFIT Academy",
          "Kolkata Runners",
          "Kottakkal Runners Club",
          "Kottayam Runners",
          "Kovaipudur Runners Club",
          "Kshitija Health",
          "Kukrail Runners",
          "L&T Runners",
          "Madras Mustang",
          "Malappuram Runners Club",
          "Marina Pacers",
          "Marina Runnerz",
          "MAVS",
          "Metrothon",
          "Mighty Warriors",
          "Mongrels",
          "Mumbai Road Runners",
          "Nellai Runners",
          "Nomadic Niligirans Running Club",
          "OMR Athletes",
          "Osian Runners",
          "Pacemakers",
          "PaceMakers",
          "Palar Runners",
          "Pinkathon",
          "Prime Runners Club",
          "Quad Runners",
          "Run for Coffee",
          "Runaddicts",
          "Runners 360",
          "Runners Academy",
          "Runners High",
          "Running Champs",
          "Runpals",
          "Salem Runners",
          "SBC Striders",
          "Scrambled Legs MDU",
          "Soles of Bengaluru",
          "Soles of Cochin",
          "Soles2Soul",
          "Soul Runners",
          "Striders",
          "Synergy Runners",
          "TCS Fit4Life",
          "Teenduruns",
          "Thala for a Reason",
          "The 5:20 Club",
          "The Trail Blazers",
          "Tirupur Runners",
          "TR Joggers",
          "Tribe Fortis",
          "Trichy Endurance Team",
          "TVT Beach Runners",
          "Udalinai Uruthi Sei",
          "UNIS Running",
          "Valeo Runners Club Move Up",
          "Vetri Fitness Club",
          "Vijayawada Runners",
          "Vizag Sole Runners",
          "VRS Runners",
          "VTRA",
          "WCCG",
          "Weekend Runners",
          "Wild Warrior / SimpleStrong",
          "Will2bwell",
          "Zen Runners",
          "Zombie Runners",
          "Others",
        ],
      },
      {
        name: "emergencyContactName",
        label: "Emergency Contact Name",
        type: "text",
      },
      {
        name: "emergencyContactRelation",
        label: "Emergency Contact Relation",
        type: "select",
        options: [
          "Spouse",
          "Parent",
          "Sibling",
          "Relative",
          "Child",
          "Friend",
          "Guardian",
        ],
      },
      {
        name: "emergencyContactNumber",
        label: "Emergency Contact Number",
        type: "tel",
      },
    ],
  },
  {
    key: "3",
    title: "Medical Questions",
    fields: [
      {
        name: "cardiovascularDisease",
        label: "Do you suffer from cardiovascular disease?",
        type: "radio",
        options: ["Yes", "No"],
      },
      {
        name: "medicalSupervision",
        label:
          "Have you been advised by doctor to engage in Physical activity only under medical supervision?",
        type: "radio",
        options: ["Yes", "No"],
      },
      {
        name: "pregnancyRisk",
        label:
          "Pregnant Women: Has this or any previous pregnancy been defined as being at risk?",
        type: "radio",
        options: ["Yes", "No"],
      },
      {
        name: "asthma",
        label: "Have you been diagnosed with asthma?",
        type: "radio",
        options: ["Yes", "No"],
      },
      {
        name: "dizziness",
        label: "Have you lost balance due to Dizziness?",
        type: "radio",
        options: ["Yes", "No"],
      },
      {
        name: "chestPain",
        label:
          "Do you suffer from Chest Pain (At Rest / Daily Activity / Physical Activity)?",
        type: "radio",
        options: ["Yes", "No"],
      },
      {
        name: "chronicIllness",
        label:
          "Do you suffer from any chronic illness not mentioned above, which limits you from Physical activities?",
        type: "radio",
        options: ["Yes", "No"],
      },
      {
        name: "otherMedicalConditions",
        label:
          "If any other specific medical conditions, please mention below:",
        type: "text",
      },
    ],
  },
  {
    key: "4",
    title: "Qualification & Waiver Form",
    fields: [
      {
        name: "timingCertificates",
        label:
          "Link to timing certificates/runner profile to demonstrate your qualification to Jawadhu Hills Ultra (races run after 01-Feb-2023)",
        type: "url",
      },
      {
        name: "para",
        text: "Read the Liability Waiver Form and Acknowledge it by clicking the checkbox at end of wavier content.",
        type: "para",
      },
      {
        name: "termsandconditions",
        type: "termsandconditions",
      },
      { name: "joinClub", type: "hidden" },
      {
        name: "waiverAcknowledgement",
        type: "hidden",
      },
    ],
  },
];
